-- Riseva — catalogue des rubriques et des indicateurs
-- ---------------------------------------------------------------------------
-- ENGENDRÉ par scripts/catalogue.mjs depuis public/app/data.js.
-- Ne pas modifier à la main : la prochaine exécution écraserait la correction.
-- Pour ajouter un indicateur, ajoutez-le dans data.js et relancez le script.
--
-- Dictionnaire version 2026.3 —
-- 8 rubriques, 27 indicateurs collectés,
-- 10 calculés.
-- ---------------------------------------------------------------------------

insert into rubrique (cle, libelle, aide, ordre, defaut) values
  ('social', 'Effectifs et mouvements', 'Ce que la paie sait déjà. C''est le dénominateur de presque tout le reste.', 1, true),
  ('securite', 'Sécurité', 'Ce que le registre du site consigne déjà, période par période.', 2, true),
  ('formation', 'Formation', 'Volume et nombre de personnes formées, toutes formations confondues.', 3, true),
  ('diversite', 'Diversité', 'Comptages simples. Aucun index réglementaire n''est calculé ici.', 4, true),
  ('energie', 'Énergie et eau', 'Les relevés de vos factures. C''est la question la plus fréquente des questionnaires clients, et celle qui traîne le plus.', 5, false),
  ('dechets', 'Déchets', 'Les tonnages de vos bordereaux d''enlèvement, site par site.', 6, false),
  ('mobilite', 'Mobilité et flotte', 'Les déplacements domicile-travail et les véhicules du site.', 7, false),
  ('achats', 'Achats', 'Le poids des fournisseurs proches et du secteur protégé dans vos achats.', 8, false)
on conflict (cle) do update set
  libelle = excluded.libelle, aide = excluded.aide,
  ordre = excluded.ordre, defaut = excluded.defaut, active = true;

insert into indicateur (cle, rubrique, libelle, unite, nature, niveau, source,
  aide, inclut, exclut, formule, numerateur, denominateur, note,
  reglementaire, ordre, version) values
  ('effectif_fin', 'social', 'Effectif à la fin de la période', 'personnes', 'collecte', 'établissement', 'paie ou DSN', 'En contrat au dernier jour de la période, tous contrats confondus.', 'CDI, CDD, apprentis et contrats de professionnalisation présents au dernier jour', 'intérimaires, stagiaires, prestataires, sous-traitants', null, null, null, null, false, 1, '2026.3'),
  ('entrees', 'social', 'Entrées', 'personnes', 'collecte', 'établissement', 'paie ou DSN', 'Embauches sur la période.', 'toute embauche sur la période, y compris en CDD', 'les mutations internes entre sites du même employeur', null, null, null, null, false, 2, '2026.3'),
  ('sorties', 'social', 'Sorties', 'personnes', 'collecte', 'établissement', 'paie ou DSN', 'Fins de contrat sur la période, quel qu''en soit le motif.', 'fins de contrat, démissions, licenciements, ruptures conventionnelles, départs en retraite, décès', 'les mutations internes entre sites du même employeur', null, null, null, null, false, 3, '2026.3'),
  ('heures_travaillees', 'social', 'Heures travaillées', 'heures', 'collecte', 'établissement', 'paie', 'Heures réellement travaillées, hors absences. C''est le dénominateur des taux de sécurité.', 'heures réellement travaillées par les personnes comptées dans l''effectif', 'congés, RTT, arrêts, formation hors poste, heures des intérimaires', null, null, null, null, false, 4, '2026.3'),
  ('at_avec_arret', 'securite', 'Accidents du travail avec arrêt', 'accidents', 'collecte', 'établissement', 'registre HSE', 'Accidents survenus sur le lieu de travail ayant entraîné un arrêt d''au moins un jour. Ce n''est pas la notion d''« accident en premier règlement » utilisée par l''assurance maladie : les taux calculés ici sont donc des indicateurs internes.', 'accidents survenus par le fait ou à l''occasion du travail, ayant entraîné au moins un jour d''arrêt au-delà du jour de l''accident', 'accidents de trajet, maladies professionnelles, accidents d''intérimaires ou de prestataires', null, null, null, null, false, 5, '2026.3'),
  ('at_sans_arret', 'securite', 'Accidents du travail sans arrêt', 'accidents', 'collecte', 'établissement', 'registre HSE', 'Accidents ayant nécessité des soins mais sans arrêt.', 'accidents ayant nécessité des soins, sans arrêt', 'les incidents sans soin, les presqu''accidents', null, null, null, null, false, 6, '2026.3'),
  ('at_trajet', 'securite', 'Accidents de trajet', 'accidents', 'collecte', 'établissement', 'registre HSE', 'Comptés à part : ils ne relèvent pas des mêmes actions de prévention.', 'accidents survenus sur le trajet domicile-travail ou vers le lieu de restauration', 'les déplacements professionnels, qui relèvent de l''accident du travail', null, null, null, null, false, 7, '2026.3'),
  ('jours_arret', 'securite', 'Journées perdues pour accident', 'jours', 'collecte', 'établissement', 'registre HSE', 'Journées calendaires d''arrêt imputables aux accidents de la période.', 'journées calendaires d''arrêt imputables aux accidents de la période, décomptées jusqu''au dernier jour de la période', 'les journées d''arrêt pour maladie ordinaire ou maladie professionnelle', null, null, null, null, false, 8, '2026.3'),
  ('formation_heures', 'formation', 'Heures de formation', 'heures', 'collecte', 'établissement', 'plan de formation', 'Toutes formations confondues.', 'toutes formations, internes et externes, sur et hors temps de travail', 'l''accueil sécurité au poste et les briefings de moins d''une heure', null, null, null, null, false, 9, '2026.3'),
  ('formation_benef', 'formation', 'Salariés formés', 'personnes', 'collecte', 'établissement', 'plan de formation', 'Personnes distinctes ayant suivi au moins une formation.', 'personnes distinctes ayant suivi au moins une formation sur la période', 'les inscriptions non suivies', null, null, null, null, false, 10, '2026.3'),
  ('femmes', 'diversite', 'Femmes dans l''effectif', 'personnes', 'collecte', 'établissement', 'paie ou DSN', 'Au dernier jour de la période.', 'personnes déclarées de sexe féminin dans la paie, au dernier jour de la période', 'les intérimaires et les prestataires', null, null, null, null, false, 11, '2026.3'),
  ('elec_kwh', 'energie', 'Électricité consommée', 'kWh', 'collecte', 'établissement', 'facture du fournisseur', 'Relevé de la période, tel qu''il figure sur vos factures.', 'la consommation du site sur la période, tous usages confondus', 'l''électricité refacturée à un tiers occupant le même bâtiment', null, null, null, null, false, 12, '2026.3'),
  ('gaz_kwh', 'energie', 'Gaz consommé', 'kWh', 'collecte', 'établissement', 'facture du fournisseur', 'En kilowattheures, tels qu''ils figurent sur la facture.', 'le gaz de réseau et le gaz en citerne', 'le gaz des chariots élévateurs, compté avec le carburant', null, null, null, null, false, 13, '2026.3'),
  ('carburant_l', 'energie', 'Carburant acheté', 'litres', 'collecte', 'établissement', 'cartes carburant', 'Fioul de chauffage et carburant des engins et véhicules du site.', 'fioul, gazole, essence et GPL achetés par le site', 'le carburant des véhicules personnels des salariés', null, null, null, null, false, 14, '2026.3'),
  ('eau_m3', 'energie', 'Eau consommée', 'm³', 'collecte', 'établissement', 'facture ou relevé de compteur', 'Relevé de la période.', 'l''eau du réseau et l''eau de forage si elle est comptée', 'l''eau de pluie récupérée et non comptée', null, null, null, null, false, 15, '2026.3'),
  ('dechets_kg', 'dechets', 'Déchets produits', 'kg', 'collecte', 'établissement', 'bordereaux d''enlèvement', 'Tonnage total enlevé sur la période, toutes filières confondues.', 'tous les déchets enlevés du site sur la période', 'les déchets d''un chantier réalisé par un tiers sur votre terrain', null, null, null, null, false, 16, '2026.3'),
  ('dechets_valorises_kg', 'dechets', 'Dont partis en valorisation', 'kg', 'collecte', 'établissement', 'bordereaux d''enlèvement', 'La part du tonnage précédent partie en recyclage, réemploi ou valorisation énergétique, selon ce qu''indique votre prestataire.', 'ce que le bordereau du prestataire déclare valorisé', 'toute estimation faite par le site lui-même', null, null, null, null, false, 17, '2026.3'),
  ('biodechets_kg', 'dechets', 'Biodéchets triés', 'kg', 'collecte', 'établissement', 'bordereaux d''enlèvement', 'Restauration collective, espaces verts, déchets alimentaires.', 'les biodéchets faisant l''objet d''un tri à la source', 'les biodéchets partis avec les ordures résiduelles', null, null, null, null, false, 18, '2026.3'),
  ('flotte', 'mobilite', 'Véhicules de la flotte du site', 'véhicules', 'collecte', 'établissement', 'parc automobile', 'Véhicules détenus ou loués par le site au dernier jour de la période.', 'voitures, utilitaires et engins immatriculés affectés au site', 'les véhicules personnels des salariés', null, null, null, null, false, 19, '2026.3'),
  ('flotte_electrique', 'mobilite', 'Dont électriques ou hybrides rechargeables', 'véhicules', 'collecte', 'établissement', 'parc automobile', 'Sous-ensemble du chiffre précédent.', 'les véhicules 100 % électriques et les hybrides rechargeables', 'les hybrides non rechargeables', null, null, null, null, false, 20, '2026.3'),
  ('places_recharge', 'mobilite', 'Points de recharge sur le site', 'points', 'collecte', 'établissement', 'services généraux', 'Bornes accessibles aux salariés, au dernier jour de la période.', 'les points de charge en service', 'les bornes installées mais non raccordées', null, null, null, null, false, 21, '2026.3'),
  ('forfait_mobilite', 'mobilite', 'Salariés au forfait mobilités durables', 'personnes', 'collecte', 'établissement', 'paie', 'Personnes ayant perçu le forfait au moins une fois sur la période.', 'les bénéficiaires effectivement payés', 'les salariés éligibles qui n''ont rien demandé', null, null, null, null, false, 22, '2026.3'),
  ('achats_montant', 'achats', 'Montant des achats du site', '€', 'collecte', 'établissement', 'comptabilité fournisseurs', 'Achats hors taxes engagés par le site sur la période.', 'les achats de biens et de services imputés au site', 'les achats du siège refacturés au site', null, null, null, null, false, 23, '2026.3'),
  ('achats_locaux', 'achats', 'Dont fournisseurs de proximité', '€', 'collecte', 'établissement', 'comptabilité fournisseurs', 'Selon la définition que vous retenez, et que le rapport reprend telle quelle.', 'les fournisseurs répondant à votre définition de la proximité', 'tout fournisseur dont l''adresse n''a pas été vérifiée', null, null, null, null, false, 24, '2026.3'),
  ('achats_esat', 'achats', 'Dont secteur du travail protégé', '€', 'collecte', 'établissement', 'comptabilité fournisseurs', 'Achats auprès d''ESAT, d''entreprises adaptées et de travailleurs indépendants handicapés.', 'les prestations facturées par ces structures sur la période', 'toute déduction d''obligation d''emploi : Riseva n''en calcule aucune', null, null, null, null, false, 25, '2026.3'),
  ('fournisseurs', 'achats', 'Fournisseurs actifs sur la période', 'fournisseurs', 'collecte', 'établissement', 'comptabilité fournisseurs', 'Nombre de fournisseurs distincts ayant facturé au moins une fois.', 'les fournisseurs ayant émis au moins une facture sur la période', 'les comptes ouverts sans mouvement', null, null, null, null, false, 26, '2026.3'),
  ('boeth', 'diversite', 'Bénéficiaires de l''obligation d''emploi présents sur le site', 'personnes', 'collecte', 'établissement', 'RH du site', 'Comptage interne, à ne pas confondre avec le taux d''emploi OETH : celui-ci se calcule une fois par an, au niveau de la société (SIREN), sur des effectifs moyens annuels Urssaf. Riseva ne le calcule pas.', 'personnes présentes sur le site ayant déclaré une reconnaissance en cours de validité', 'toute inférence : ce comptage repose sur des déclarations volontaires, et un salarié n''a aucune obligation de déclarer', null, null, null, null, false, 27, '2026.3'),
  ('tf1', 'securite', 'Fréquence interne des accidents avec arrêt', null, 'calcule', 'tout périmètre', null, null, null, null, 'accidents avec arrêt × 1 000 000 ÷ heures travaillées', 'at_avec_arret', 'heures_travaillees', 'Indicateur interne. Le taux de fréquence de l''assurance maladie repose sur les accidents en premier règlement : ces deux chiffres ne se comparent pas.', false, 101, '2026.3'),
  ('tf2', 'securite', 'Fréquence interne, avec et sans arrêt', null, 'calcule', 'tout périmètre', null, null, null, null, '(accidents avec arrêt + sans arrêt) × 1 000 000 ÷ heures travaillées', 'at_avec_arret + at_sans_arret', 'heures_travaillees', 'Indicateur interne, utile pour suivre les presqu''accidents soignés sans arrêt.', false, 102, '2026.3'),
  ('tg', 'securite', 'Gravité interne', null, 'calcule', 'tout périmètre', null, null, null, null, 'journées perdues × 1 000 ÷ heures travaillées', 'jours_arret', 'heures_travaillees', 'Indicateur interne. Les journées perdues déclarées ici ne suivent pas forcément les règles d''imputation de l''assurance maladie.', false, 103, '2026.3'),
  ('if_', 'securite', 'Indice interne de fréquence', null, 'calcule', 'tout périmètre', null, null, null, null, 'accidents avec arrêt × 1 000 ÷ effectif', 'at_avec_arret', 'effectif_fin', 'Indicateur interne.', false, 104, '2026.3'),
  ('turnover', 'social', 'Rotation du personnel', '%', 'calcule', 'tout périmètre', null, null, null, null, '(entrées + sorties) ÷ 2 ÷ effectif × 100', '(entrees + sorties) / 2', 'effectif_fin', 'Définition interne : il en existe plusieurs, celle-ci est écrite pour être refaite à la main.', false, 105, '2026.3'),
  ('part_femmes', 'diversite', 'Part des femmes dans l''effectif', '%', 'calcule', 'tout périmètre', null, null, null, null, 'femmes ÷ effectif × 100', 'femmes', 'effectif_fin', 'Ne préjuge en rien de l''index d''égalité professionnelle, qui obéit à d''autres règles et se calcule au niveau de l''entreprise.', false, 106, '2026.3'),
  ('part_valorise', 'dechets', 'Part des déchets valorisés', '%', 'calcule', 'tout périmètre', null, null, null, null, 'déchets valorisés ÷ déchets produits × 100', 'dechets_valorises_kg', 'dechets_kg', 'Reprend la qualification du prestataire d''enlèvement, sans la vérifier.', false, 107, '2026.3'),
  ('part_flotte_elec', 'mobilite', 'Part électrique de la flotte', '%', 'calcule', 'tout périmètre', null, null, null, null, 'véhicules électriques ou hybrides rechargeables ÷ flotte × 100', 'flotte_electrique', 'flotte', 'Comptage de véhicules, pas de kilomètres parcourus.', false, 108, '2026.3'),
  ('part_achats_locaux', 'achats', 'Part des achats de proximité', '%', 'calcule', 'tout périmètre', null, null, null, null, 'achats de proximité ÷ achats du site × 100', 'achats_locaux', 'achats_montant', 'Dépend entièrement de la définition de proximité retenue par l''entreprise, qui est reprise à côté du chiffre dans le rapport.', false, 109, '2026.3'),
  ('elec_par_salarie', 'energie', 'Électricité par salarié', 'kWh', 'calcule', 'tout périmètre', null, null, null, null, 'électricité consommée ÷ effectif', 'elec_kwh', 'effectif_fin', 'Rapporter à l''effectif permet de comparer deux sites de tailles différentes. Ce ratio n''a aucun sens entre un entrepôt et un bureau.', false, 110, '2026.3')
on conflict (cle) do update set
  rubrique = excluded.rubrique, libelle = excluded.libelle, unite = excluded.unite,
  nature = excluded.nature, niveau = excluded.niveau, source = excluded.source,
  aide = excluded.aide, inclut = excluded.inclut, exclut = excluded.exclut,
  formule = excluded.formule, numerateur = excluded.numerateur,
  denominateur = excluded.denominateur, note = excluded.note,
  reglementaire = excluded.reglementaire, ordre = excluded.ordre,
  version = excluded.version, active = true;

-- Ce qui a quitté le catalogue est désactivé, jamais supprimé : les valeurs
-- déjà saisies sous cette clé restent lisibles, et les rapports qui les citent
-- restent vrais.
update indicateur set active = false where cle not in ('effectif_fin', 'entrees', 'sorties', 'heures_travaillees', 'at_avec_arret', 'at_sans_arret', 'at_trajet', 'jours_arret', 'formation_heures', 'formation_benef', 'femmes', 'elec_kwh', 'gaz_kwh', 'carburant_l', 'eau_m3', 'dechets_kg', 'dechets_valorises_kg', 'biodechets_kg', 'flotte', 'flotte_electrique', 'places_recharge', 'forfait_mobilite', 'achats_montant', 'achats_locaux', 'achats_esat', 'fournisseurs', 'boeth', 'tf1', 'tf2', 'tg', 'if_', 'turnover', 'part_femmes', 'part_valorise', 'part_flotte_elec', 'part_achats_locaux', 'elec_par_salarie');
update rubrique  set active = false where cle not in ('social', 'securite', 'formation', 'diversite', 'energie', 'dechets', 'mobilite', 'achats');
